# Generated by Django 2.2.12 on 2021-02-12 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='available',
            field=models.BooleanField(default='Yes'),
        ),
    ]
